name: "Pull Request Docs Check"
on: 
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: alliander-opensource/short-term-forecasting@main
      with:
        docs-folder: "docs/"
