# SPDX-FileCopyrightText: 2017-2021 Alliander N.V.
#
# SPDX-License-Identifier: MPL-2.0
name: Docs Check

on:
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - name: Checkout code
      uses: actions/checkout@v1
    # Install
    - name: Install dependencies
      run: |
        pip install sphinx_rtd_theme
    # Build documentation
    - name: Build documentation
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "cp requirements.txt docs/requirements.txt | sphinx-apidoc -o docs openstf"
        docs-folder: "docs/"
