# SPDX-FileCopyrightText: 2017-2021 Alliander N.V. <korte.termijn.prognoses@alliander.com> # noqa E501
#
# SPDX-License-Identifier: MPL-2.0
name: Python Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    # Checkout
    - name: Checkout code
      uses: actions/checkout@v2
    # Setup
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    # Restore
    - name: Restore pip cache
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    # Install
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
    # Very limited linting with Flake8 (see setup.cfg for configuration)
    - name: Lint
      run: |
        # Stop build on a couple more serious violations
        # See https://flake8.pycqa.org/en/latest/user/error-codes.html for more details
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Only print warnings on all other errors
        flake8 . --count --exit-zero --show-source --statistics
    # Test
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest test
    # Build
    - name: Build Python package
      run: |
        python setup.py sdist bdist_wheel
