# SPDX-FileCopyrightText: 2017-2022 Contributors to the OpenSTEF project <korte.termijn.prognoses@alliander.com> # noqa E501
#
# SPDX-License-Identifier: MPL-2.0

name: Release

on:
  push:
    branches:
      - main
  # pull_request event is required only for autolabeler
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]

jobs:
  # Releases new Python version when Pull Requests are merged into "main"
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
      # Setup
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # Bump and commit version. The upload to pypi step happens after github release.
      - name: Bump version and commit bumped version back to branch
        id: version
        run: |
          version=$(python .github/bump_version.py)
          git config --global user.name 'bump_version'
          git config --global user.email 'action@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git fetch
          git checkout main
          git commit --signoff -am "Bumped minor version"
          git push
          echo "BUMPED_VERSION=$(echo v$version)" >> $GITHUB_ENV
          echo "New version: $version"
      # Create new release
      - name: Create Release
        run: gh release create ${{ env.BUMPED_VERSION }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
